In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [3]:
df=pd.read_csv('Churn_Modelling.csv')

In [4]:
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [6]:
df.drop(columns=['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [7]:
df

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [8]:
label_encoder_gender=LabelEncoder()
df['Gender']=label_encoder_gender.fit_transform(df['Gender'])

In [9]:
df

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [11]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [15]:
oh_encoder_geo=OneHotEncoder()
geo_encoder=oh_encoder_geo.fit_transform(df[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [16]:
type(geo_encoder)

scipy.sparse._csr.csr_matrix

In [20]:
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(),columns=oh_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [23]:
data=pd.concat([geo_encoded_df,df.drop(columns=['Geography'])],axis=1)
data.head()

   Geography_France  Geography_Germany  ...  EstimatedSalary  Exited
0               1.0                0.0  ...        101348.88       1
1               0.0                0.0  ...        112542.58       0
2               1.0                0.0  ...        113931.57       1
3               1.0                0.0  ...         93826.63       0
4               0.0                0.0  ...         79084.10       0

[5 rows x 13 columns]

In [28]:
# Save the encoders and scaler
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(oh_encoder_geo,file)

In [32]:
X=data.drop(columns=['Exited'],axis=1)
Y=data['Exited']

In [33]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=140)

In [34]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [35]:
X_train

array([[ 0.9951546 , -0.5764705 , -0.57449099, ...,  0.63688499,
        -1.03282415, -1.53694464],
       [ 0.9951546 , -0.5764705 , -0.57449099, ...,  0.63688499,
         0.96821904,  1.21744088],
       [ 0.9951546 , -0.5764705 , -0.57449099, ...,  0.63688499,
        -1.03282415, -1.2772539 ],
       ...,
       [ 0.9951546 , -0.5764705 , -0.57449099, ...,  0.63688499,
        -1.03282415,  1.37730715],
       [ 0.9951546 , -0.5764705 , -0.57449099, ...,  0.63688499,
         0.96821904, -0.13345934],
       [ 0.9951546 , -0.5764705 , -0.57449099, ...,  0.63688499,
         0.96821904, -1.11636796]])

In [37]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

### ANN Implementation

In [46]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [43]:
X_train.shape[1]

12

In [48]:
# Build ANN model

model=Sequential(
    [
        Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
        Dense(32,activation='relu'),
        Dense(1,activation='sigmoid'),
    ]
)

In [50]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_1 (Dense)             (None, 64)                832

 dense_2 (Dense)             (None, 32)                2080

 dense_3 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [56]:
keras_opt=keras.optimizers.Adam(learning_rate=0.01)
keras_loss=keras.losses.BinaryCrossentropy()

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

In [57]:
# Compile the model
model.compile(optimizer=keras_opt,loss=keras_loss,metrics=['accuracy'])

In [59]:
# Setup the tensorboard

log_dir='logs/fit'+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [60]:
# Setup early stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [61]:
# Training the model

history=model.fit(X_train,Y_train,validation_data=[X_test,Y_test],epochs=100,callbacks=[tensorboard_callback,early_stopping_callback])

Epoch 1/100
219/219 [==============================] - 1s 1ms/step - loss: 0.3954 - accuracy: 0.8351 - val_loss: 0.3722 - val_accuracy: 0.8447
Epoch 2/100
219/219 [==============================] - 0s 705us/step - loss: 0.3483 - accuracy: 0.8579 - val_loss: 0.3796 - val_accuracy: 0.8460
Epoch 3/100
219/219 [==============================] - 0s 587us/step - loss: 0.3401 - accuracy: 0.8567 - val_loss: 0.3613 - val_accuracy: 0.8530
Epoch 4/100
219/219 [==============================] - 0s 575us/step - loss: 0.3358 - accuracy: 0.8626 - val_loss: 0.3652 - val_accuracy: 0.8573
Epoch 5/100
219/219 [==============================] - 0s 588us/step - loss: 0.3332 - accuracy: 0.8629 - val_loss: 0.3614 - val_accuracy: 0.8513
Epoch 6/100
219/219 [==============================] - 0s 603us/step - loss: 0.3330 - accuracy: 0.8654 - val_loss: 0.3615 - val_accuracy: 0.8550
Epoch 7/100
219/219 [==============================] - 0s 572us/step - loss: 0.3259 - accuracy: 0.8680 - val_loss: 0.3743 - val_accuracy: 0.8510
Epoch 8/100
219/219 [==============================] - 0s 591us/step - loss: 0.3291 - accuracy: 0.8639 - val_loss: 0.3619 - val_accuracy: 0.8503

In [62]:
model.save('model.h5')

/Users/subhadipsamanta/Desktop/Folder V1.0/AI & ML/deep_learning_projects/ann_classification/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [65]:
# Load tensorboard extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [70]:
%tensorboard --logdir logs/fit20250518-184354

Reusing TensorBoard on port 6007 (pid 5057), started 0:00:14 ago. (Use '!kill 5057' to kill it.)