In [43]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras.models import load_model
import pickle

In [44]:
## Load all train models
model=load_model('model.h5')

## Load the encoders and scaler
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)

with open('onehot_encoder_geo.pkl','rb') as file:
    onehot_encoder_geo=pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

In [45]:
# Example input data

input_data={
    'CreditScore':600,
    'Geography':'France',
    'Gender':'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

In [46]:
input_df=pd.DataFrame([input_data])

In [47]:
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])

In [32]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [33]:
geo_encoded=onehot_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

/Users/subhadipsamanta/Desktop/Folder V1.0/AI & ML/deep_learning_projects/ann_classification/venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [34]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [35]:
input_df=pd.concat([geo_encoded_df,input_df.drop(columns=['Geography'],axis=1)],axis=1)
input_df

,Geography_France,Geography_Germany,Geography_Spain,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,1.0,0.0,0.0,600,1,40,3,60000,2,1,1,50000

In [36]:
input_scaled=scaler.transform(input_df)
input_scaled

array([[ 0.9951546 , -0.5764705 , -0.57449099, -0.53935946,  0.91528831,
         0.10933937, -0.68704449, -0.25872059,  0.79310274,  0.63688499,
         0.96821904, -0.8766178 ]])

In [37]:
prediction=model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 208ms/step

array([[0.04364185]], dtype=float32)

In [38]:
prediction_prob=prediction[0][0]

In [40]:
prediction_prob

0.043641854

In [41]:
if prediction_prob>0.5:
    print('Customer is not likely to churn')
else:
    print('Customer is likely to churn')

Customer is likely to churn